FROM genesix/golang-build as builder

WORKDIR /app

COPY . .

RUN make build

FROM alpine:3.11

LABEL maintainer="dortiz@devops.faith"

COPY --from=builder /app/krakend /usr/bin/krakend

RUN addgroup -S krakend && adduser -S -G krakend krakend

USER krakend

VOLUME [ "/etc/krakend" ]

ENTRYPOINT [ "/usr/bin/krakend" ]
CMD [ "run", "-c", "/etc/krakend/krakend.json" ]

EXPOSE 8000 8090
